// =============================================================================
// tb_systolic_8x8.sv — 8x8 Systolic Array + Skew Buffer Integration Testbench
//
// VERIFICATION FLOW:
//   1. Load 8x8 test vectors (A, B, C_ref) generated by gemm_ref.py using $readmemh.
//   2. Phase 1 (Weight Load): Stream B into systolic array (load_wgt = 1).
//   3. Phase 2 (Compute): Feed unskewed activation rows into skew_buffer.
//      - skew_buffer automatically delays row i by i cycles in hardware.
//   4. Phase 3 (Capture & Verify): Sample psum_out at exact cycle T(r, c) = r + c + 8.
//   5. Compare all 64 output elements against golden reference C_ref_8x8.
//   6. Report pass/fail statistics, print matrices, and assert on any mismatch.
// =============================================================================

`timescale 1ns/1ps

module tb_systolic_8x8;

    localparam int N          = 8;
    localparam int DATA_WIDTH = 8;
    localparam int ACC_WIDTH  = 32;

    // DUT Signals
    logic                          clk      = 0;
    logic                          rst_n    = 0;
    logic                          load_wgt = 0;

    logic signed [DATA_WIDTH-1:0]  wgt_in      [N];
    logic signed [ACC_WIDTH-1:0]   psum_top    [N];
    logic signed [DATA_WIDTH-1:0]  flat_in     [N];
    wire  signed [DATA_WIDTH-1:0]  act_skewed  [N];
    wire  signed [ACC_WIDTH-1:0]   psum_out    [N];

    // Test vectors and memory storage
    logic signed [DATA_WIDTH-1:0] A_mem     [0:N*N-1];
    logic signed [DATA_WIDTH-1:0] B_mem     [0:N*N-1];
    logic signed [ACC_WIDTH-1:0]  C_ref_mem [0:N*N-1];

    logic signed [DATA_WIDTH-1:0] A        [0:N-1][0:N-1];
    logic signed [DATA_WIDTH-1:0] B        [0:N-1][0:N-1];
    logic signed [ACC_WIDTH-1:0]  C_ref    [0:N-1][0:N-1];
    logic signed [ACC_WIDTH-1:0]  C_actual [0:N-1][0:N-1];

    int pass_count = 0;
    int fail_count = 0;

    // -------------------------------------------------------------------------
    // Clock generation: 100MHz (10ns period)
    // -------------------------------------------------------------------------
    always #5 clk = ~clk;

    // -------------------------------------------------------------------------
    // Module Instantiations
    // -------------------------------------------------------------------------
    skew_buffer #(
        .N          (N),
        .DATA_WIDTH (DATA_WIDTH)
    ) u_skew_buffer (
        .clk      (clk),
        .rst_n    (rst_n),
        .flat_in  (flat_in),
        .skew_out (act_skewed)
    );

    systolic_array #(
        .N          (N),
        .DATA_WIDTH (DATA_WIDTH),
        .ACC_WIDTH  (ACC_WIDTH)
    ) u_systolic_array (
        .clk      (clk),
        .rst_n    (rst_n),
        .load_wgt (load_wgt),
        .wgt_in   (wgt_in),
        .psum_top (psum_top),
        .act_in   (act_skewed),
        .psum_out (psum_out)
    );

    // -------------------------------------------------------------------------
    // Verification Helper Tasks
    // -------------------------------------------------------------------------
    task automatic check_element(
        input int r,
        input int c,
        input logic signed [ACC_WIDTH-1:0] got,
        input logic signed [ACC_WIDTH-1:0] expected
    );
        if (got === expected) begin
            $display("  [PASS] C[%0d][%0d] = %0d (expected %0d)", r, c, got, expected);
            pass_count++;
        end else begin
            $display("  [FAIL] C[%0d][%0d] MISMATCH! Got: %0d (hex %08h), Expected: %0d (hex %08h), Diff: %0d",
                     r, c, got, got, expected, expected, got - expected);
            fail_count++;
        end
    endtask

    // -------------------------------------------------------------------------
    // Main Test Sequence
    // -------------------------------------------------------------------------
    initial begin
        $display("\n================================================================================");
        $display(" 8x8 Weight-Stationary Systolic Array + Hardware Skew Buffer Verification");
        $display("================================================================================");

        // 1. Read test vectors
        $readmemh("sim/vectors/A_8x8.hex", A_mem);
        $readmemh("sim/vectors/B_8x8.hex", B_mem);
        $readmemh("sim/vectors/C_ref_8x8.hex", C_ref_mem);

        // Reshape 1D vector memories into 2D matrices
        for (int r = 0; r < N; r++) begin
            for (int c = 0; c < N; c++) begin
                A[r][c]        = A_mem[r*N + c];
                B[r][c]        = B_mem[r*N + c];
                C_ref[r][c]    = C_ref_mem[r*N + c];
                C_actual[r][c] = '0;
            end
        end

        $display("\n--- Matrix A (Activations) (8x8 INT8) ---");
        for (int r = 0; r < N; r++) begin
            $write("  [");
            for (int c = 0; c < N; c++) begin
                $write(" %4d", A[r][c]);
            end
            $display(" ]");
        end

        $display("\n--- Matrix B (Weights) (8x8 INT8) ---");
        for (int r = 0; r < N; r++) begin
            $write("  [");
            for (int c = 0; c < N; c++) begin
                $write(" %4d", B[r][c]);
            end
            $display(" ]");
        end

        $display("\n--- Golden Reference Matrix C = A x B (8x8 INT32) ---");
        for (int r = 0; r < N; r++) begin
            $write("  [");
            for (int c = 0; c < N; c++) begin
                $write(" %7d", C_ref[r][c]);
            end
            $display(" ]");
        end

        // Initialize inputs
        rst_n    = 0;
        load_wgt = 0;
        for (int i = 0; i < N; i++) begin
            wgt_in[i]   = '0;
            psum_top[i] = '0;
            flat_in[i]  = '0;
        end

        // 2. Reset sequence
        repeat(3) @(posedge clk);
        #1 rst_n = 1;
        @(posedge clk);

        // ---------------------------------------------------------------------
        // PHASE 1: Load Weights into Systolic Array
        // Stream rows from B[N-1] down to B[0] into wgt_in
        // ---------------------------------------------------------------------
        $display("\n--------------------------------------------------------------------------------");
        $display("[PHASE 1] Loading Weights B (8 cycles)...");
        $display("--------------------------------------------------------------------------------");

        for (int r = N - 1; r >= 0; r--) begin
            #1;
            load_wgt = 1;
            for (int c = 0; c < N; c++) begin
                wgt_in[c] = B[r][c];
            end
            @(posedge clk);
        end

        // Deassert weight load
        #1;
        load_wgt = 0;
        for (int c = 0; c < N; c++) begin
            wgt_in[c] = '0;
        end
        $display("  [+] Weights successfully latched in stationary registers.");

        // ---------------------------------------------------------------------
        // PHASE 2 & 3: Feed Activations & Check Outputs
        // Feed unskewed matrix A rows (cycle 0..7). Skew buffer handles skewing.
        // Sample outputs at T(r, c) = r + c + 8 (cycles 8..22).
        // ---------------------------------------------------------------------
        $display("\n--------------------------------------------------------------------------------");
        $display("[PHASE 2 & 3] Streaming Activations through Skew Buffer & Verifying Output C...");
        $display("--------------------------------------------------------------------------------");

        for (int cycle = 0; cycle <= (3 * N); cycle++) begin
            #1;
            // Feed unskewed activation row during cycles 0..N-1
            if (cycle < N) begin
                for (int c = 0; c < N; c++) begin
                    flat_in[c] = A[cycle][c];
                end
            end else begin
                for (int c = 0; c < N; c++) begin
                    flat_in[c] = '0;
                end
            end

            // Check any matrix output elements emerging at current cycle
            for (int r = 0; r < N; r++) begin
                for (int c = 0; c < N; c++) begin
                    if ((r + c + N) == cycle) begin
                        C_actual[r][c] = psum_out[c];
                        check_element(r, c, psum_out[c], C_ref[r][c]);
                    end
                end
            end

            @(posedge clk);
        end

        // ---------------------------------------------------------------------
        // Final Results Summary
        // ---------------------------------------------------------------------
        $display("\n--- Hardware Computed Matrix C (8x8 INT32) ---");
        for (int r = 0; r < N; r++) begin
            $write("  [");
            for (int c = 0; c < N; c++) begin
                $write(" %7d", C_actual[r][c]);
            end
            $display(" ]");
        end

        $display("\n================================================================================");
        $display(" VERIFICATION RESULTS: %0d / 64 PASSED, %0d FAILED", pass_count, fail_count);
        $display("================================================================================");

        if (fail_count == 0 && pass_count == 64) begin
            $display("\n  *** ALL 64 MATRIX ELEMENTS MATCH GOLDEN REFERENCE EXACTLY! [SUCCESS] ***\n");
        end else begin
            $display("\n  *** VERIFICATION FAILED WITH %0d ERRORS! ***\n", fail_count);
            $fatal(1, "Testbench failed due to output mismatch.");
        end

        $finish;
    end

    initial begin
        $dumpfile("sim/vectors/wave_systolic_8x8.vcd");
        $dumpvars(0, tb_systolic_8x8);
    end

endmodule
